csad2425ki404panurinas14: src/main.cpp File Reference
main.cpp File Reference
#include <ArduinoJson.h>
Functions
String moveToString (int choice)
Converts a numeric choice to its corresponding move in the game "Rock, Paper, Scissors".
float relu (float x)
Applies the Rectified Linear Unit (ReLU) activation function.
void softmax (float x[], int size)
Computes the softmax of an array of floats.
String predict ()
Predicts the next move in a rock-paper-scissors game based on the last moves.
String randomChoice ()
Generates a random choice for a rock-paper-scissors game.
int playerChoiceToInt (String choice)
Converts the player's choice from a string to an integer.
void addPlayerMove (int newMove)
Adds a new player move to the list of last moves.
void setup ()
void loop ()
Main loop function that reads from the serial input, processes JSON data, and determines the winner of a rock-paper-scissors game.
Variables
JsonDocument doc
String jsonString
JsonDocument winConditions
int lastMoves [3]
float inputWeights [3][8]
float hiddenWeights [8][3]
float hiddenBias [8] = {-0.211966, 0.226446, -0.129866, 0.805082, 0.822114, -0.379106, -0.669373, 1.362221}
float outputBias [3] = {-0.727954, 0.467537, 0.264352}
Function Documentation
addPlayerMove()
void addPlayerMove (int newMove)
Adds a new player move to the list of last moves.
This function shifts the existing moves in the lastMoves array to the right and inserts the new move at the beginning of the array. The oldest move is discarded if the array is full.
Parameters
newMove The new move to be added to the list of last moves.
Definition at line 171 of file main.cpp.
{
    for (int i = 3 - 1; i > 0; --i) {
        lastMoves[i] = lastMoves[i - 1];
    }
    lastMoves[0] = newMove;
}
References lastMoves.
loop()
void loop ()
Main loop function that reads from the serial input, processes JSON data, and determines the winner of a rock-paper-scissors game.
This function continuously checks for available data on the serial input. When data is available, it reads characters and appends them to a JSON string. Once a complete JSON object is detected (indicated by the '}' character), it attempts to deserialize the JSON string into a JsonDocument.
If deserialization fails, it sends an error message back via the serial output. If successful, it extracts player choices from the JSON document. If a player choice is missing, it generates a random choice or predicts the next move based on previous moves.
The function then determines the winner based on predefined win conditions and sends the result back via the serial output in JSON format.
Note
The function assumes the existence of several helper functions and variables:
randomChoice(): Generates a random choice for the player.
predict(): Predicts the next move based on previous moves.
addPlayerMove(int): Records the player's move.
playerChoiceToInt(String): Converts a player's choice to an integer.
winConditions: A map or dictionary that defines the win conditions.
Definition at line 214 of file main.cpp.
{
    while (Serial.available())
    {
        char c = Serial.read();
        jsonString += c;
        if (c == '}')
        {
            DeserializationError error = deserializeJson(doc, jsonString);
            JsonDocument response;
            String resp = "";
            if (error)
            {
                response["error"] = "Failed to parse JSON";
                serializeJson(response, resp);
                Serial.println(resp);
                return;
            }
            jsonString = "";
            String player1Choice = doc["player1Choice"];
            String player2Choice = doc["player2Choice"];
            if (!doc["player1Choice"])
            {
                player1Choice = randomChoice();
            }
            if (!doc["player2Choice"])
            {
                if (!doc["player1Choice"])
                {
                    player2Choice = randomChoice();
                }
                else
                {
                    player2Choice = predict();
                    addPlayerMove(playerChoiceToInt(player1Choice));
                }
            }
            int winner = 2;
            if (player1Choice == player2Choice)
            {
                winner = 3;
            }
            else if (winConditions[player1Choice] == player2Choice)
            {
                winner = 1;
            }
            response["winner"] = winner;
            response["player1Choice"] = player1Choice;
            response["player2Choice"] = player2Choice;
            serializeJson(response, resp);
            Serial.println(resp);
        }
    }
}
References addPlayerMove(), doc, jsonString, playerChoiceToInt(), predict(), randomChoice(), and winConditions.
moveToString()
String moveToString (int choice)
Converts a numeric choice to its corresponding move in the game "Rock, Paper, Scissors".
Parameters
choice An integer representing the player's choice: 0 for Rock, 1 for Paper, 2 for Scissors.
Returns
String The corresponding move as a string ("Rock", "Paper", or "Scissors").
Definition at line 36 of file main.cpp.
{
    if (choice == 0)
        return "Rock";
    if (choice == 1)
        return "Paper";
    return "Scissors";
}
playerChoiceToInt()
int playerChoiceToInt (String choice)
Converts the player's choice from a string to an integer.
This function takes a string representing the player's choice in a rock-paper-scissors game and converts it to an integer. The mapping is as follows:
"Rock" -> 0
"Paper" -> 1
"Scissors" -> 2
Parameters
choice The player's choice as a string. It should be one of "Rock", "Paper", or "Scissors".
Returns
int The integer representation of the player's choice.
Definition at line 153 of file main.cpp.
{
    if (choice == "Rock")
        return 0;
    if (choice == "Paper")
        return 1;
    return 2;
}
predict()
String predict ()
Predicts the next move in a rock-paper-scissors game based on the last moves.
This function uses a simple neural network with one hidden layer to predict the next move. The network consists of an input layer with 3 neurons, a hidden layer with 8 neurons, and an output layer with 3 neurons. The activation function used in the hidden layer is ReLU, and the output layer uses softmax to produce probabilities.
Returns
A string representing the predicted move ("rock", "paper", or "scissors").
Definition at line 92 of file main.cpp.
{
    float output[3];
    float hiddenLayer[8];
    for (int i = 0; i < 8; i++)
    {
        hiddenLayer[i] = hiddenBias[i];
        for (int j = 0; j < 3; j++)
        {
            hiddenLayer[i] += lastMoves[j] * inputWeights[j][i];
        }
        hiddenLayer[i] = relu(hiddenLayer[i]);
    }
    for (int i = 0; i < 3; i++)
    {
        output[i] = outputBias[i];
        for (int j = 0; j < 8; j++)
        {
            output[i] += hiddenLayer[j] * hiddenWeights[j][i];
        }
    }
    softmax(output, 3);
    int best_move = 0;
    if (output[1] > output[best_move])
        best_move = 1;
    if (output[2] > output[best_move])
        best_move = 2;
    return moveToString(best_move);
}
References hiddenBias, hiddenWeights, inputWeights, lastMoves, moveToString(), outputBias, relu(), and softmax().
randomChoice()
String randomChoice ()
Generates a random choice for a rock-paper-scissors game.
This function generates a random integer between 0 and 2 (inclusive), converts it to the corresponding string representation of "rock", "paper", or "scissors", and returns it.
Returns
String The string representation of the random choice.
Definition at line 136 of file main.cpp.
{
    return moveToString(random(3));
}
References moveToString().
relu()
float relu (float x)
Applies the Rectified Linear Unit (ReLU) activation function.
The ReLU function returns the input value if it is greater than zero, otherwise it returns zero. It is commonly used in neural networks to introduce non-linearity.
Parameters
x The input value.
Returns
The output of the ReLU function.
Definition at line 55 of file main.cpp.
{
    return x > 0 ? x : 0;
}
setup()
void setup ()
Definition at line 179 of file main.cpp.
{
    Serial.begin(9600);
    winConditions["Rock"] = "Scissors";
    winConditions["Scissors"] = "Paper";
    winConditions["Paper"] = "Rock";
    for (int i = 0; i < 3; i++)
    {
        lastMoves[i] = random(3);
    }
}
References lastMoves, and winConditions.
softmax()
void softmax (float x[], int size)
Computes the softmax of an array of floats.
The softmax function is a type of squashing function that maps an input array of real numbers to an array of values between 0 and 1 that sum to 1. This is often used in machine learning for converting raw scores (logits) into probabilities.
Parameters
x The input array of floats. The array is modified in place to contain the softmax values.
size The size of the input array.
Definition at line 70 of file main.cpp.
{
    float max_val = x[0];
    for (int i = 1; i < size; i++)
        if (x[i] > max_val)
            max_val = x[i];
    float sum = 0;
    for (int i = 0; i < size; i++)
        sum += exp(x[i] - max_val);
    for (int i = 0; i < size; i++)
        x[i] = exp(x[i] - max_val) / sum;
}
Variable Documentation
doc
JsonDocument doc
Definition at line 3 of file main.cpp.
hiddenBias
float hiddenBias[8] = {-0.211966, 0.226446, -0.129866, 0.805082, 0.822114, -0.379106, -0.669373, 1.362221}
Definition at line 24 of file main.cpp.
{-0.211966, 0.226446, -0.129866, 0.805082, 0.822114, -0.379106, -0.669373, 1.362221};
hiddenWeights
float hiddenWeights[8][3]
Initial value:
= {
    {0.804684, -1.282053, 0.335981},
    {-0.450472, -0.130367, -0.340924},
    {0.617688, -1.746359, 0.093773},
    {-1.098668, 0.399702, 0.018028},
    {-0.327865, 0.498658, 0.591891},
    {0.278758, -0.548902, -0.742056},
    {1.374351, -1.441604, -0.971736},
    {-1.804082, 1.326259, -0.090229},
}
Definition at line 14 of file main.cpp.
{
    {0.804684, -1.282053, 0.335981},
    {-0.450472, -0.130367, -0.340924},
    {0.617688, -1.746359, 0.093773},
    {-1.098668, 0.399702, 0.018028},
    {-0.327865, 0.498658, 0.591891},
    {0.278758, -0.548902, -0.742056},
    {1.374351, -1.441604, -0.971736},
    {-1.804082, 1.326259, -0.090229},
};
inputWeights
float inputWeights[3][8]
Initial value:
= {
    {0.153426, 0.547693, 0.122109, 0.439899, 0.546894, 0.439505, 0.145383, 0.257606},
    {0.171111, -0.401668, 0.069744, -0.851256, 0.667974, 0.300057, 0.103562, 0.678151},
    {1.111694, -0.009917, 1.976872, 0.006001, 0.115645, 0.364659, 0.940397, -0.902065},
}
Definition at line 9 of file main.cpp.
{
    {0.153426, 0.547693, 0.122109, 0.439899, 0.546894, 0.439505, 0.145383, 0.257606},
    {0.171111, -0.401668, 0.069744, -0.851256, 0.667974, 0.300057, 0.103562, 0.678151},
    {1.111694, -0.009917, 1.976872, 0.006001, 0.115645, 0.364659, 0.940397, -0.902065},
};
jsonString
String jsonString
Definition at line 4 of file main.cpp.
lastMoves
int lastMoves[3]
Definition at line 7 of file main.cpp.
outputBias
float outputBias[3] = {-0.727954, 0.467537, 0.264352}
Definition at line 25 of file main.cpp.
{-0.727954, 0.467537, 0.264352};
winConditions
JsonDocument winConditions
Definition at line 5 of file main.cpp.